trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo $(date)
      - bash: ls -lrta $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)